export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "C++"
  | "C#"
  | "PL/SQL"
  | "UI/UX Design"
  | "Adobe Illustrator"
  | "Photoshop"
  | "InDesign"
  | "Flutter"
  | "Dart"
  | "Mongoose"
  | "JWT"
  | "Tesseract.js"
  | "Vite"
  | "React Router"
  | "scikit-learn"
  | "pandas"
  | "Jupyter"
  | "GridFS"
  | "Unity"
  | "Google Gemini"
  | "Studio One"
  | "Vegas Pro"
  | "Canva"
  | "CapCut"
  | "3ds Max";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "Branding"
  | "Audiovisual"
  | "Video/Photo Editing"
  | "AI/ML"
  | "Game Dev"
  | "Print Design";

export type ValidExpType = "Personal" | "Professional";

// Top-level split used by the Projects page to separate code-based work
// (web/mobile/game dev) from design & multimedia work.
export type ValidPortfolioCategory = "development" | "creative";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "resume";
